name: "Lint"
on:
  pull_request:
      types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Pace repository
          uses: actions/checkout@v3.5.2
        - name: Step Python 3.8.12
          uses: actions/setup-python@v4.6.0
          with:
            python-version: '3.8.12'
        - name: Install Python packages
          run: |
            python -m pip install --upgrade pip
            pip install -r pace/requirements_dev.txt pace/requirements_lint.txt
        - name: Run lint via pre-commit
          run: |
            cd pace
            pre-commit run --all-files

